os: linux
dist: xenial
language: java

env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest

jdk:
  - openjdk12

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
  - tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C $HOME/bin

script:
  - mvn clean test
